### ISSUE TITLE
ImportError: No module named 'secrets'

### ISSUE THREAD

**Issue by RafayelGardishyan** [RafayelGardishyan/CLGE#5]
## Expected Behavior
CLGETests.py should generate test reandom integers with python secrets lib.

## Actual Behavior
ImportError: No module named 'secrets'

## Specifications

  - Platform: Linux
  - Subsystem: IDK (Travis CI)

**Comment by kiranfrancis94** [comment]
Are you trying to use the command '**import secrets**' inorder to get a secret key?
If so, try the following commands. These commands will create a secret key for you:

$ python

import os
os.urandom(24)

These commands will create a secret key, which you can be used

**Comment by RafayelGardishyan** [comment]
No, I use it because Codacy wants me to use a not pseudo random generator. It's only needed to generate random coordinates
